TICKERS_SP_100 = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "GOOG",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "BRK-B",
    "UNH",
    "LLY",
    "JPM",
    "V",
    "XOM",
    "AVGO",
    "PG",
    "JNJ",
    "MA",
    "HD",
    "CVX",
    "MRK",
    "ABBV",
    "PEP",
    "KO",
    "COST",
    "ADBE",
    "CRM",
    "TMO",
    "BAC",
    "ACN",
    "CSCO",
    "WMT",
    "MCD",
    "ABT",
    "LIN",
    "DIS",
    "VZ",
    "NFLX",
    "CMCSA",
    "WFC",
    "DHR",
    "ORCL",
    "PM",
    "TXN",
    "NKE",
    "RTX",
    "UPS",
    "BMY",
    "MS",
    "SCHW",
    "AMD",
    "IBM",
    "SPGI",
    "CAT",
    "GE",
    "AMGN",
    "INTU",
    "GS",
    "BLK",
    "PLD",
    "DE",
    "UNP",
    "LOW",
    "MDT",
    "ISRG",
    "AMT",
    "SYK",
    "CVS",
    "MO",
    "CI",
    "AXP",
    "BKNG",
    "ADI",
    "PYPL",
    "CB",
    "MMC",
    "NOW",
    "T",
    "GILD",
    "ELV",
    "SO",
    "EOG",
    "DUK",
    "ZTS",
    "PGR",
    "BDX",
    "SLB",
    "HON",
    "ETN",
    "APD",
    "CL",
    "ITW",
    "SHW",
    "BSX",
    "FISV",
    "WM",
    "GD",
    "NOC",
    "MCK",
    "PSX",
]

TICKERS_SP_50 = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "GOOG",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "BRK-B",
    "UNH",
    "LLY",
    "JPM",
    "V",
    "XOM",
    "AVGO",
    "PG",
    "JNJ",
    "MA",
    "HD",
    "CVX",
    "MRK",
    "ABBV",
    "PEP",
    "KO",
    "COST",
    "ADBE",
    "CRM",
    "TMO",
    "BAC",
    "ACN",
    "CSCO",
    "WMT",
    "MCD",
    "ABT",
    "LIN",
    "DIS",
    "VZ",
    "NFLX",
    "CMCSA",
    "WFC",
    "DHR",
    "ORCL",
    "PM",
    "TXN",
    "NKE",
    "RTX",
    "UPS",
    "BMY",
    "MS",
    "SCHW",
]

TICKERS_SP_20 = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "GOOG",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "BRK-B",
    "UNH",
    "LLY",
    "JPM",
    "V",
    "XOM",
    "AVGO",
    "PG",
    "JNJ",
    "MA",
    "HD",
    "CVX",
]

TICKERS_SP_10 = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "GOOG",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "BRK-B",
    "UNH",
]

TICKER_TO_COMPANY = {
    "AAPL": "apple",
    "MSFT": "microsoft",
    "GOOGL": "google",
    "GOOG": "google",
    "AMZN": "amazon",
    "NVDA": "nvidia",
    "META": "meta",
    "TSLA": "tesla",
    "BRK-B": "berkshire hathaway",
    "UNH": "unitedhealth",
    "LLY": "lilly",
    "JPM": "jpmorgan",
    "V": "visa",
    "XOM": "exxon",
    "AVGO": "broadcom",
    "PG": "procter and gamble",
    "JNJ": "johnson and johnson",
    "MA": "mastercard",
    "HD": "home depot",
    "CVX": "chevron",
    "MRK": "merck",
    "ABBV": "abbvie",
    "PEP": "pepsi",
    "KO": "coca-cola",
    "COST": "costco",
    "ADBE": "adobe",
    "CRM": "salesforce",
    "TMO": "thermo fisher",
    "BAC": "bank of america",
    "ACN": "accenture",
    "CSCO": "cisco",
    "WMT": "walmart",
    "MCD": "mcdonalds",
    "ABT": "abbott",
    "LIN": "linde",
    "DIS": "disney",
    "VZ": "verizon",
    "NFLX": "netflix",
    "CMCSA": "comcast",
    "WFC": "wells fargo",
    "DHR": "danaher",
    "ORCL": "oracle",
    "PM": "philip morris",
    "TXN": "texas instruments",
    "NKE": "nike",
    "RTX": "raytheon technologies",
    "UPS": "ups",
    "BMY": "bristol-myers squibb",
    "MS": "morgan stanley",
    "SCHW": "schwab",
    "AMD": "amd",
    "IBM": "ibm",
    "SPGI": "s&p global",
    "CAT": "caterpillar",
    "GE": "general electric",
    "AMGN": "amgen",
    "INTU": "intuit",
    "GS": "goldman sachs",
    "BLK": "blackrock",
    "PLD": "prologis",
    "DE": "deere",
    "UNP": "union pacific",
    "LOW": "lowes",
    "MDT": "medtronic",
    "ISRG": "intuitive surgical",
    "AMT": "american tower",
    "SYK": "stryker",
    "CVS": "cvs",
    "MO": "altria",
    "CI": "cigna",
    "AXP": "american express",
    "BKNG": "booking",
    "ADI": "analog devices",
    "PYPL": "paypal",
    "CB": "chubb",
    "MMC": "marsh & mclennan",
    "NOW": "servicenow",
    "T": "att",
    "GILD": "gilead",
    "ELV": "elevance health",
    "SO": "southern company",
    "EOG": "eog resources",
    "DUK": "duke energy",
    "ZTS": "zoetis",
    "PGR": "progressive",
    "BDX": "becton dickinson",
    "SLB": "schlumberger",
    "HON": "honeywell",
    "ETN": "eaton",
    "APD": "air products",
    "CL": "colgate-palmolive",
    "ITW": "illinois tool works",
    "SHW": "sherwin-williams",
    "BSX": "boston scientific",
    "FISV": "fiserv",
    "WM": "waste management",
    "GD": "general dynamics",
    "NOC": "northrop grumman",
    "MCK": "mckesson",
    "PSX": "phillips 66",
}

HARD_EVENT_KEYWORDS = [
    "acquire",
    "acquires",
    "acquisition",
    "merger",
    "merge",
    "buyout",
    "takeover",
    "sale of",
    "spin-off",
    "spinoff",
    "bankruptcy",
    "chapter 11",
    "restructuring",
    "lawsuit",
    "settlement",
    "court",
    "investigation",
    "sec investigation",
    "doj investigation",
    "antitrust",
    "regulator",
    "approval",
    "fda approval",
    "rejected",
    "denied",
    "contract",
    "partnership",
    "deal",
    "agreement",
    "earnings miss",
    "earnings beat",
    "profit warning",
    "guidance cut",
    "guidance raised",
    "forecast cut",
    "forecast raised",
]

FINANCIAL_KEYWORDS = [
    "revenue",
    "sales",
    "profit",
    "loss",
    "cash flow",
    "free cash flow",
    "margin",
    "operating margin",
    "cost cutting",
    "layoffs",
    "job cuts",
    "headcount reduction",
    "dividend",
    "dividend cut",
    "dividend increase",
    "share buyback",
    "stock buyback",
    "debt",
    "credit rating",
    "downgrade",
    "upgrade",
]

PRODUCT_KEYWORDS = [
    "launch",
    "released",
    "rollout",
    "new product",
    "product launch",
    "patent",
    "intellectual property",
    "drug trial",
    "clinical trial",
    "phase 1",
    "phase 2",
    "phase 3",
    "manufacturing issue",
    "recall",
    "supply chain disruption",
]

MANAGEMENT_KEYWORDS = [
    "ceo resigns",
    "ceo steps down",
    "cfo resigns",
    "management change",
    "board change",
    "insider buying",
    "insider selling",
]

IMPORTANT_KEYWORDS = (
    HARD_EVENT_KEYWORDS + FINANCIAL_KEYWORDS + PRODUCT_KEYWORDS + MANAGEMENT_KEYWORDS
)
