from sections.price_performance_section import PricePerformanceSection


class TestPricePerformanceSection:
    """Test class for Price performance section."""

    def test__generate_report_part__builder_string_returned(
        self,
        mock_price_performance_manager,
        mock_price_performance_builder,
        create_section_data,
    ):
        """Check if instantiating and calling generate function returns a string generated by a builder."""
        section = PricePerformanceSection(create_section_data)
        assert section.generate() == "Builder md string"
