from sections.news_section import NewsSection


class TestNewsSection:
    """Test class for News section."""

    def test__generate_report_part__builder_string_returned(
        self, mock_news_manager, mock_news_builder, create_section_data
    ):
        """Check if instantiating and calling generate function returns a string generated by a builder."""
        section = NewsSection(create_section_data)
        assert section.generate() == "Builder md string"
