from sections.insider_section import InsiderSection


class TestInsiderSection:
    """Test class for Insider section."""

    def test__generate_report_part__builder_string_returned(
        self, mock_insider_manager, mock_insider_builder, create_section_data
    ):
        """Check if instantiating and calling generate function returns a string generated by a builder."""
        section = InsiderSection(create_section_data)
        assert section.generate() == "Builder md string"
