from sections.analyst_section import AnalystSection


class TestAnalystSection:
    """Test class for Analyst section."""

    def test__generate_report_part__builder_string_returned(
        self, mock_analyst_manager, mock_analyst_builder, create_section_data
    ):
        """Check if instantiating and calling generate function returns a string generated by a builder."""
        section = AnalystSection(create_section_data)
        assert section.generate() == "Builder md string"
