from sections.earnings_section import EarningsSection


class TestEarningsSection:
    """Test class for Earnings section."""

    def test__generate_report_part__builder_string_returned(
        self, mock_earnings_manager, mock_earnings_builder, create_section_data
    ):
        """Check if instantiating and calling generate function returns a string generated by a builder."""
        section = EarningsSection(create_section_data)
        assert section.generate() == "Builder md string"
